apiVersion: apps/v1
kind: Deployment
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asynqmon
  template:
    metadata:
      labels:
        app: asynqmon
    spec:
      containers:
      - name: asynqmon
        image: hibiken/asynqmon:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_ADDR
          value: "redis:6379"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: asynqmon
  labels:
    app: asynqmon
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: asynqmon
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: asynqmon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: asynqmon.ohkajhu.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: asynqmon
            port:
              number: 8080
